// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arrrmerugnlxvlbjrcoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycnJtZXJ1Z25seHZsYmpyY295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTIxNzksImV4cCI6MjA3NDU2ODE3OX0.ekCSXoptb-1OIEuuLmpS_WbsjHW3xUHo1heeaGxV8Ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});